import { ImageItem } from './types';

export const DEMO_IMAGES: ImageItem[] = [
  {
    id: '1',
    url: 'https://picsum.photos/id/1015/800/600',
    thumbnail: 'https://picsum.photos/id/1015/400/300',
    prompt: 'A breathtaking landscape of a river valley at sunset with terraced rice fields.',
    category: 'Landscape',
    tags: ['sunset', 'river', 'nature'],
    width: 800,
    height: 600,
  },
  {
    id: '2',
    url: 'https://picsum.photos/id/1025/600/800',
    thumbnail: 'https://picsum.photos/id/1025/300/400',
    prompt: 'A cute pug wrapped in a cozy blanket wearing oversized glasses.',
    category: 'Animals',
    tags: ['dog', 'cute', 'portrait'],
    width: 600,
    height: 800,
  },
  {
    id: '3',
    url: 'https://picsum.photos/id/1035/800/800',
    thumbnail: 'https://picsum.photos/id/1035/400/400',
    prompt: 'A hiker standing on top of a mountain looking at a waterfall.',
    category: 'Adventure',
    tags: ['hiking', 'waterfall', 'outdoors'],
    width: 800,
    height: 800,
  },
  {
    id: '4',
    url: 'https://picsum.photos/id/106/800/500',
    thumbnail: 'https://picsum.photos/id/106/400/250',
    prompt: 'Cyberpunk city street at night with neon signs and rain.',
    category: 'Sci-Fi',
    tags: ['cyberpunk', 'neon', 'city'],
    width: 800,
    height: 500,
  },
  {
    id: '5',
    url: 'https://picsum.photos/id/1074/600/900',
    thumbnail: 'https://picsum.photos/id/1074/300/450',
    prompt: 'A close-up of a lioness staring intensely with golden eyes.',
    category: 'Animals',
    tags: ['lion', 'wildlife', 'intense'],
    width: 600,
    height: 900,
  },
  {
    id: '6',
    url: 'https://picsum.photos/id/16/800/600',
    thumbnail: 'https://picsum.photos/id/16/400/300',
    prompt: 'A calm lake reflecting the mountains and sky in the morning mist.',
    category: 'Landscape',
    tags: ['lake', 'reflection', 'peaceful'],
    width: 800,
    height: 600,
  },
  {
    id: '7',
    url: 'https://picsum.photos/id/237/600/800',
    thumbnail: 'https://picsum.photos/id/237/300/400',
    prompt: 'A black puppy playing in the grass.',
    category: 'Animals',
    tags: ['puppy', 'playful', 'grass'],
    width: 600,
    height: 800,
  },
  {
    id: '8',
    url: 'https://picsum.photos/id/301/800/500',
    thumbnail: 'https://picsum.photos/id/301/400/250',
    prompt: 'An old rusty boat stranded on a sandy beach.',
    category: 'Abstract',
    tags: ['boat', 'beach', 'rusty'],
    width: 800,
    height: 500,
  },
];

export const CATEGORIES = ['All', 'Landscape', 'Animals', 'Sci-Fi', 'Adventure', 'Abstract', 'Portrait'];
