import React from 'react';

const FAQ: React.FC = () => {
  return (
    <div className="min-h-screen bg-background text-textPrimary pt-8 pb-20 px-6 page-enter">
      <div className="max-w-3xl mx-auto">
        
        <header className="mb-12 text-center">
          <h1 className="text-3xl md:text-4xl font-bold mb-4 text-textPrimary">Frequently Asked Questions</h1>
          <p className="text-textSecondary">
            Everything you need to know about ProGall, Prompt Engineering, and usage rights.
          </p>
        </header>

        <div className="space-y-6">
          
          <div className="bg-surface border border-surfaceHighlight rounded-2xl p-6">
            {/* FIX: Changed text-white to text-textPrimary */}
            <h3 className="text-lg font-bold text-textPrimary mb-2">What is ProGall?</h3>
            <p className="text-textSecondary text-sm leading-relaxed">
              ProGall is a premium community gallery for AI enthusiasts. We curate high-quality images generated by tools like Midjourney, Stable Diffusion, and DALL-E, and provide the exact prompt used to create them.
            </p>
          </div>

          <div className="bg-surface border border-surfaceHighlight rounded-2xl p-6">
            {/* FIX: Changed text-white to text-textPrimary */}
            <h3 className="text-lg font-bold text-textPrimary mb-2">Is ProGall free to use?</h3>
            <p className="text-textSecondary text-sm leading-relaxed">
              Yes! Browsing, copying prompts, and downloading images for inspiration is completely free. We believe in open access to AI education.
            </p>
          </div>

          <div className="bg-surface border border-surfaceHighlight rounded-2xl p-6">
            {/* FIX: Changed text-white to text-textPrimary */}
            <h3 className="text-lg font-bold text-textPrimary mb-2">Can I use these prompts for commercial projects?</h3>
            <p className="text-textSecondary text-sm leading-relaxed">
              Absolutely. Prompts themselves are generally not copyrighted. You are free to copy our prompts, modify them, and use the resulting images for your own commercial or personal projects.
            </p>
          </div>

          <div className="bg-surface border border-surfaceHighlight rounded-2xl p-6">
            {/* FIX: Changed text-white to text-textPrimary */}
            <h3 className="text-lg font-bold text-textPrimary mb-2">How do I verify the prompt works?</h3>
            <p className="text-textSecondary text-sm leading-relaxed">
              AI generation is probabilistic, meaning you might get slightly different results even with the same prompt. We recommend copying the prompt and tweaking specific keywords (like lighting or colors) to fit your specific vision.
            </p>
          </div>

          <div className="bg-surface border border-surfaceHighlight rounded-2xl p-6">
            {/* FIX: Changed text-white to text-textPrimary */}
            <h3 className="text-lg font-bold text-textPrimary mb-2">How can I contact the team?</h3>
            <p className="text-textSecondary text-sm leading-relaxed">
              You can reach us through our Contact page or via our social media channels linked in the footer. We typically respond within 24-48 hours.
            </p>
          </div>

        </div>
      </div>
    </div>
  );
};

export default FAQ;
