import React, { useEffect, useState } from 'react';
import SEO from '../components/SEO';
import { ChevronDown, ChevronUp } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ_DATA: FAQItem[] = [
  {
    question: 'What is ProGall?',
    answer: 'ProGall is a premium community gallery for AI art enthusiasts and prompt engineers. We curate high-quality images generated by tools like Midjourney, Stable Diffusion, DALL-E 3, and Google Gemini, and provide the exact prompt used to create each piece. Our goal is to eliminate "blank canvas syndrome" by giving creators a proven starting point for every style and subject.',
  },
  {
    question: 'Is ProGall free to use?',
    answer: 'Yes — completely. Browsing the gallery, copying prompts, and using them in your own projects is 100% free, with no subscription or sign-up required. We believe that access to quality AI art education should be open to everyone. We plan to keep core features free indefinitely.',
  },
  {
    question: 'Can I use these prompts for commercial projects?',
    answer: 'Absolutely. Text prompts are not protected by copyright under current law, which means you are free to copy, modify, and use our prompts in both commercial and personal projects. The resulting AI-generated images may have their own licensing considerations depending on the platform you use (e.g. Midjourney\'s commercial license requires a paid plan). Always check your AI platform\'s terms of service for image ownership rules.',
  },
  {
    question: 'How do I use a prompt from ProGall?',
    answer: 'It is simple: (1) Find an image you like and click it to open the detail page. (2) Click "Copy Prompt" to copy the full text to your clipboard. (3) Open your preferred AI tool — Midjourney, DALL-E 3, Stable Diffusion, or Gemini. (4) Paste the prompt and generate. You can then refine the output by tweaking specific keywords, adjusting lighting terms, or swapping the subject while keeping the stylistic modifiers.',
  },
  {
    question: 'Why do my results look different from the example image?',
    answer: 'AI generation is probabilistic — even an identical prompt will produce slightly different results on each run. This is because generative models use random "seeds" during the diffusion process. Additionally, results vary significantly between platforms (Midjourney vs DALL-E vs Stable Diffusion) and even between model versions. We recommend running the prompt 3–5 times and selecting the best result. You can also use the Troubleshooting section on each image detail page for specific tips on faces, colors, and composition.',
  },
  {
    question: 'What is prompt engineering and why does it matter?',
    answer: 'Prompt engineering is the practice of crafting precise text instructions to guide AI models toward a desired output. In generative AI, the quality of your prompt is the single biggest factor determining output quality. A well-engineered prompt includes: (1) a clear primary subject, (2) lighting and atmosphere modifiers, (3) camera angle or art style keywords, and (4) quality boosters. ProGall is designed to teach prompt engineering through example — every image in our gallery demonstrates a specific, effective technique.',
  },
  {
    question: 'Which AI tools work with ProGall prompts?',
    answer: 'Our prompts are designed to work across all major AI image generators: Midjourney (v5, v6, niji), DALL-E 3 via ChatGPT or Bing Image Creator, Stable Diffusion (SDXL, 1.5), and Google Gemini. Each platform has its own strengths — Midjourney excels at artistic styles, DALL-E 3 at following literal instructions, and Stable Diffusion at fine-grained control. Each image detail page on ProGall includes a compatibility score to help you pick the best tool for that specific style.',
  },
  {
    question: 'How do I get better results with Midjourney specifically?',
    answer: 'For Midjourney, we recommend these tips: (1) Use --v 6 or --v 6.1 for the latest model. (2) Add --style raw for a more photographic, less over-processed look. (3) Add --ar 16:9 for landscape, --ar 2:3 for portrait. (4) Use --q 2 for maximum quality (takes longer). (5) For anime, switch to --niji 6. (6) Add a --no parameter to exclude unwanted elements (e.g. --no watermark, blurry, text). These flags can dramatically improve the output of any ProGall prompt.',
  },
  {
    question: 'What are negative prompts and should I use them?',
    answer: 'Negative prompts tell the AI what to exclude from the generated image. They are a powerful tool in Stable Diffusion (entered in the "Negative Prompt" field) and can be approximated in Midjourney using the --no flag. Common effective negative prompts include: "blurry, low quality, deformed, extra fingers, watermark, text, oversaturated, flat lighting." Using negatives alongside a ProGall prompt typically increases consistency and reduces artifacts, especially for portraits and character art.',
  },
  {
    question: 'How often is the gallery updated?',
    answer: 'We continuously add new prompts to the gallery, with a focus on emerging styles and the latest AI model capabilities. You can always find the newest additions by sorting by "Latest" on the image detail page\'s "More to Explore" section. We monitor updates to Midjourney, DALL-E, Stable Diffusion, and Gemini closely and update our category guides and prompt styles to reflect new capabilities as they are released.',
  },
  {
    question: 'Can I submit my own prompts to the gallery?',
    answer: 'We are currently working on a community submission feature. For now, if you have an exceptional prompt you would like to share with the ProGall community, you can reach out to us via the Contact page. Our curators manually review each submission for quality and accuracy before adding it to the gallery.',
  },
  {
    question: 'How can I contact the ProGall team?',
    answer: 'You can reach us through our Contact page or via our social media channels (Instagram and Threads: @progall_). We typically respond within 24–48 hours. For technical issues with the site, bug reports are especially helpful and we prioritise them.',
  },
];

const FAQAccordionItem: React.FC<{ item: FAQItem; index: number }> = ({ item, index }) => {
  const [isOpen, setIsOpen] = useState(index === 0);
  return (
    <div className="bg-surface border border-border/50 rounded-2xl overflow-hidden">
      <button
        onClick={() => setIsOpen(v => !v)}
        className="w-full flex items-center justify-between px-6 py-5 text-left hover:bg-surfaceHighlight/50 transition-colors"
        aria-expanded={isOpen}
      >
        <h3 className="text-base font-semibold text-textPrimary pr-4">{item.question}</h3>
        {isOpen
          ? <ChevronUp size={18} className="text-accent shrink-0" />
          : <ChevronDown size={18} className="text-textSecondary shrink-0" />
        }
      </button>
      {isOpen && (
        <div className="px-6 pb-5 text-textSecondary text-sm leading-relaxed border-t border-border/30 pt-4">
          {item.answer}
        </div>
      )}
    </div>
  );
};

const FAQ: React.FC = () => {
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <div className="min-h-screen bg-background text-textPrimary pt-32 pb-20 px-6 page-enter">
      <SEO
        title="FAQ — AI Prompt Engineering Questions Answered"
        description="Answers to common questions about ProGall, prompt engineering, how to use AI art prompts, Midjourney tips, Stable Diffusion guide, and usage rights."
        url="https://progall.tech/faq"
      />

      <div className="max-w-3xl mx-auto">

        <header className="mb-12 text-center">
          <h1 className="text-3xl md:text-4xl font-bold mb-4 text-textPrimary">Frequently Asked Questions</h1>
          <p className="text-textSecondary max-w-xl mx-auto leading-relaxed">
            Everything you need to know about ProGall, AI prompt engineering, and how to get the best results from Midjourney, DALL-E 3, Stable Diffusion, and Google Gemini.
          </p>
        </header>

        <div className="space-y-3">
          {FAQ_DATA.map((item, i) => (
            <FAQAccordionItem key={i} item={item} index={i} />
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="mt-16 p-8 bg-surface border border-border/50 rounded-2xl text-center">
          <p className="text-textPrimary font-semibold text-lg mb-2">Still have questions?</p>
          <p className="text-textSecondary text-sm mb-6">
            Our team is happy to help. Reach out via the contact page and we'll get back to you within 24 hours.
          </p>
          <a
            href="/contact"
            className="inline-flex items-center gap-2 px-6 py-3 bg-accent text-white font-bold rounded-xl hover:opacity-90 transition-all text-sm"
          >
            Contact Us
          </a>
        </div>

      </div>
    </div>
  );
};

export default FAQ;
